# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrabflixPremium' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'youtube-ios-player-helper'
  pod 'Firebase'
  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

end
